version: '3'
services:
  db:
    image: postgres:9.5
    ports:
      - '34199:5432'
    volumes:
      - './support/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: part_test
      POSTGRES_PASSWORD: postgres
